- FarmFarm/src/main/webapp/resources/css/productManage/orderDetail.css
- FarmFarm/src/main/webapp/resources/css/productManage/productOrderList-style.css
- FarmFarm/src/main/webapp/resources/html/productManage/orderDetail.html
- FarmFarm/src/main/webapp/resources/html/productManage/productOrderList.html
> Product order detail

- FarmFarm/src/main/webapp/resources/css/productManage/orderDetail.css
- FarmFarm/src/main/webapp/resources/html/productManage/orderDetail.html
> 주문 상세조회 페이지 화면 완료

- FarmFarm/src/main/webapp/WEB-INF/views/common/footer.jsp
- FarmFarm/src/main/webapp/resources/css/productManage/stockManage-style.css
- FarmFarm/src/main/webapp/resources/html/productManage/stockManage.html
> Stock detail 현재

- FarmFarm/src/main/java/edu/kh/farmfarm/productList/controller/ProductListController.java
- FarmFarm/src/main/webapp/resources/html/postList/postList.html
> 1221 GetMapping 오류 수정

- FarmFarm/src/main/webapp/resources/css/order/cart-style.css
- FarmFarm/src/main/webapp/resources/html/order/cart.html
> Cart page 현재

- FarmFarm/src/main/webapp/WEB-INF/views/board/boardWrite.jsp
- FarmFarm/src/main/webapp/resources/css/board/boardWrite-style.css
- FarmFarm/src/main/webapp/resources/js/board/boardWrite.js
> Board write 도은

- FarmFarm/src/main/java/edu/kh/farmfarm/seller/controller/SellerController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/seller/model/dao/SellerDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/seller/model/service/SellerService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/seller/model/service/SellerServiceImpl.java
- FarmFarm/src/main/resources/mappers/seller-mapper.xml
- FarmFarm/src/main/webapp/resources/js/seller/sellerPage.js
> Seller page 현재

- FarmFarm/src/main/resources/mappers/postList-mapper.xml
> postlist sold out 정렬

- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/controller/ProductAdminController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/model/dao/ProductAdminDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/model/service/ProductAdminService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/model/service/ProductAdminServiceImpl.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productDetail/model/vo/Product.java
- FarmFarm/src/main/resources/mappers/productAdmin-mapper.xml
- FarmFarm/src/main/webapp/WEB-INF/views/productAdmin/productStock.jsp
- FarmFarm/src/main/webapp/resources/css/productAdmin/productStock-style.css
> 상품관리 페이지 상품 불러오기

- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/controller/ProductAdminController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/model/dao/ProductAdminDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/model/service/ProductAdminService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productAdmin/model/service/ProductAdminServiceImpl.java
- FarmFarm/src/main/resources/mappers/productAdmin-mapper.xml
- FarmFarm/src/main/webapp/WEB-INF/views/productAdmin/productStock.jsp
- FarmFarm/src/main/webapp/resources/css/productAdmin/productStock-style.css
- FarmFarm/src/main/webapp/resources/js/productAdmin/productStock.js
> Product list 현재

- FarmFarm/src/main/java/edu/kh/farmfarm/common/SearchItem.java
- FarmFarm/src/main/java/edu/kh/farmfarm/postList/controller/PostListController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/postList/model/dao/PostListDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/postList/model/service/PostListService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/postList/model/service/PostListServiceImpl.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productDetail/model/vo/Product.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productList/controller/ProductListController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productList/model/dao/ProductListDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productList/model/service/ProductListService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/productList/model/service/ProductListServiceImpl.java
- FarmFarm/src/main/resources/mappers/postList-mapper.xml
- FarmFarm/src/main/resources/mappers/productList-mapper.xml
- FarmFarm/src/main/webapp/WEB-INF/views/postList/postList.jsp
- FarmFarm/src/main/webapp/WEB-INF/views/productList/productList.jsp
- FarmFarm/src/main/webapp/resources/css/postList/postList-style.css
- FarmFarm/src/main/webapp/resources/css/productList/productList-style.css
- FarmFarm/src/main/webapp/resources/js/postList/postList.js
- FarmFarm/src/main/webapp/resources/js/productList/productList.js
> 상품 목록 페이지 품절 제거 옵션 추가

- FarmFarm/src/main/java/edu/kh/farmfarm/alarm/model/vo/Alarm.java
- FarmFarm/src/main/resources/mappers/alarm-mapper.xml
- FarmFarm/src/main/webapp/WEB-INF/views/common/header.jsp
> 230101 알림 insert문 수정

- FarmFarm/src/main/java/edu/kh/farmfarm/alarm/controller/AlarmController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/alarm/model/dao/AlarmDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/alarm/model/service/AlarmService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/alarm/model/service/AlarmServiceImpl.java
- FarmFarm/src/main/resources/mappers/alarm-mapper.xml
- FarmFarm/src/main/webapp/WEB-INF/views/common/header.jsp
- FarmFarm/src/main/webapp/resources/css/alarm/alarmWidget-style.css
- FarmFarm/src/main/webapp/resources/css/common/header-style.css
> 220101 알림 목록 기능

- FarmFarm/src/main/java/edu/kh/farmfarm/board/controller/BoardListController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/dao/BoardListDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/service/BoardListService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/service/BoardListServiceImpl.java
- FarmFarm/src/main/resources/mappers/board-mapper.xml
- FarmFarm/src/main/webapp/WEB-INF/views/board/boardList.jsp
- FarmFarm/src/main/webapp/resources/css/board/boardList-style.css
- FarmFarm/src/main/webapp/resources/js/board/boardList.js
> Board modify 도은

- FarmFarm/src/main/webapp/resources/js/chat2/chatCenter.js
> 채팅 초대하기 수정

- FarmFarm/src/main/webapp/resources/js/chat2/chatService.js
- FarmFarm/src/main/webapp/resources/js/chat2/chatWidget.js
> 이모티콘, 이미지의 채팅방 목록 출력 방식 지정

- FarmFarm/src/main/resources/mappers/chat2-mapper.xml
> 230109 조회수 증가 sql 수정

- FarmFarm/src/main/webapp/resources/js/productList/productList.js
> 230110 상품 검색 시 카테고리 초기화 오류 수정

- FarmFarm/src/main/webapp/resources/js/chat2/chatContext.js
> 230111 채팅 신고 모달 오류 수정

- FarmFarm/src/main/java/edu/kh/farmfarm/board/controller/BoardDetailController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/controller/CommentController.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/dao/BoardDetailDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/dao/CommentDAO.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/service/BoardDetailService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/service/BoardDetailServiceImpl.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/service/CommentService.java
- FarmFarm/src/main/java/edu/kh/farmfarm/board/model/service/CommentServiceImpl.java
- FarmFarm/src/main/webapp/WEB-INF/views/board/boardDetail.jsp
- FarmFarm/src/main/webapp/WEB-INF/views/board/boardList.jsp
- FarmFarm/src/main/webapp/WEB-INF/views/board/boardUpdate.jsp
- FarmFarm/src/main/webapp/WEB-INF/views/board/boardWrite.jsp
- FarmFarm/src/main/webapp/WEB-INF/views/board/comment.jsp
- FarmFarm/src/main/webapp/resources/js/board/boardDetail.js
- FarmFarm/src/main/webapp/resources/js/board/boardList.js
- FarmFarm/src/main/webapp/resources/js/board/boardUpdate.js
- FarmFarm/src/main/webapp/resources/js/board/boardWrite.js
- FarmFarm/src/main/webapp/resources/js/board/comment.js
> 20230222-주석 수정

- FarmFarm/src/main/java/edu/kh/farmfarm/chat2/controller/Chat2Controller.java
- FarmFarm/src/main/java/edu/kh/farmfarm/chat2/model/service/Chat2Service.java
- FarmFarm/src/main/java/edu/kh/farmfarm/chat2/model/service/Chat2ServiceImpl.java
- FarmFarm/src/main/java/edu/kh/farmfarm/chat2/model/websocket/Chat2WebsocketHandler.java
- FarmFarm/src/main/webapp/resources/js/chat2/chatContext.js
- FarmFarm/src/main/webapp/resources/js/chat2/chatService.js
- FarmFarm/src/main/webapp/resources/js/chat2/emoticon.js
> 230305 채팅 사진 삭제 오류, 날짜 오류 수정
